#!/usr/bin/env node
/* ===================================================================
   Regenerate /sitemap.xml from the pages on disk and /data/*.json
   ===================================================================
   WHY THIS EXISTS
     Every event and update needs to be in the sitemap, and this site
     has no build step -- Netlify just uploads files. A hand-edited
     sitemap.xml would be stale the first time the director adds an
     event and forgets the XML. So the sitemap is generated instead.

     This is NOT a build step. Nothing runs it on deploy. Run it
     yourself after adding or publishing content:

       node tools/build-sitemap.js

     It prints what it wrote, and exits non-zero on malformed JSON so a
     broken data file cannot quietly produce a truncated sitemap.

   WHAT GOES IN
     - The static pages listed in PAGES below.
     - Every PUBLISHED event, as event.html?id=...
     - Every PUBLISHED post, as post.html?slug=...

     Unpublished entries are skipped. A draft is not a public URL, and
     listing one invites Google to index a page that renders a redirect.

   WHAT STAYS OUT
     Internal and no-index pages: styleguide.html, data-preview.html,
     thank-you.html, 404.html. Pages staged as `ready: false` in
     assets/site.js are also out until they are real.
=================================================================== */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ORIGIN = "https://tysfuturestars.org";

/* changefreq/priority are hints search engines largely ignore now, so
   this keeps only what they actually read: loc and lastmod. */
const PAGES = [
  "index.html",
  "about.html",
  "ty-story.html",
  "programs.html",
  "get-involved.html",
  "whats-happening.html",
  "where-your-money-goes.html",
  "resources.html",
  "donate.html",
  "contact.html",
  "privacy.html",
  "terms.html"
];

/* Staged in the nav as ready:false -- not linked, so not listed. Add
   the page here when you flip it on in assets/site.js. */
const STAGED = ["impact.html"];

function readJson(rel) {
  const file = path.join(ROOT, rel);
  if (!fs.existsSync(file)) {
    console.warn("  skip  " + rel + " (not found)");
    return [];
  }
  try {
    const rows = JSON.parse(fs.readFileSync(file, "utf8"));
    if (!Array.isArray(rows)) throw new Error("must contain an array");
    return rows;
  } catch (err) {
    console.error("ERROR  " + rel + ": " + err.message);
    process.exit(1);
  }
}

function published(rows) {
  return rows.filter((r) => r && r.published === true);
}

/* An ISO day if the entry has a usable one, otherwise the file's own
   mtime. Never today's date -- claiming everything changed today is
   the kind of noise that gets a sitemap ignored. */
function isoDay(value) {
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}/.test(value)) {
    return value.slice(0, 10);
  }
  return null;
}

function fileDate(rel) {
  const file = path.join(ROOT, rel);
  if (!fs.existsSync(file)) return null;
  return fs.statSync(file).mtime.toISOString().slice(0, 10);
}

function xmlEscape(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function urlEntry(loc, lastmod) {
  return (
    "  <url>\n" +
    "    <loc>" + xmlEscape(loc) + "</loc>\n" +
    (lastmod ? "    <lastmod>" + lastmod + "</lastmod>\n" : "") +
    "  </url>"
  );
}

function main() {
  const entries = [];

  PAGES.forEach((page) => {
    const loc = ORIGIN + "/" + (page === "index.html" ? "" : page);
    entries.push(urlEntry(loc, fileDate(page)));
  });

  const events = published(readJson("data/events.json"));
  events.forEach((e) => {
    if (!e.id) return;
    entries.push(urlEntry(
      ORIGIN + "/event.html?id=" + encodeURIComponent(e.id),
      isoDay(e.endDate) || isoDay(e.date)
    ));
  });

  const posts = published(readJson("data/posts.json"));
  posts.forEach((p) => {
    if (!p.slug) return;
    entries.push(urlEntry(
      ORIGIN + "/post.html?slug=" + encodeURIComponent(p.slug),
      isoDay(p.date)
    ));
  });

  const xml =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    "<!-- Generated by tools/build-sitemap.js. Do not hand-edit:\n" +
    "     run `node tools/build-sitemap.js` after publishing content. -->\n" +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    entries.join("\n") + "\n" +
    "</urlset>\n";

  fs.writeFileSync(path.join(ROOT, "sitemap.xml"), xml);

  console.log("sitemap.xml written");
  console.log("  " + PAGES.length + " static pages");
  console.log("  " + events.length + " published events");
  console.log("  " + posts.length + " published updates");
  console.log("  " + entries.length + " URLs total");
  if (STAGED.length) {
    console.log("  excluded (staged ready:false): " + STAGED.join(", "));
  }
  if (!events.length && !posts.length) {
    console.log("\n  Note: nothing is published in events.json or posts.json,");
    console.log("  so no event or update URLs are listed yet. Re-run this");
    console.log("  after setting published:true on real entries.");
  }
}

main();
